name: Produce packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Each build should be different because of the $RANDOM addition
      - name: Build latest
        run: |
          for ((i=1; i<=5; i++))
          do
            imageName="ghcr.io/snok/container-retention-policy:test-${i}"
            randomString=$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 10)
            echo "\
          FROM alpine as builder

          RUN echo \"$randomString\" > test.txt

          FROM scratch

          COPY --from=builder /test.txt ." > Dockerfile
            docker buildx build -f Dockerfile -t $imageName --push .

            for ((j=1; j<=3; j++))
            do
              newName="ghcr.io/snok/container-retention-policy:test-${i}-${j}"
              docker tag $imageName $newName
              docker push $newName
            done
          done
